name: Build and Deploy to FTP (develop branches) # Workflow-Name

on:
  push:
    branches:
      - '*develop*' # Triggert bei Push auf Branches mit "develop" im Namen

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Verwende die neueste Ubuntu-Umgebung
    environment: Deploy # <-- Add this line

    steps:
      - name: Checkout repository
        # Klont das Repository in den Runner
        uses: actions/checkout@v4

      - name: Set up Hugo
        # Installiert Hugo in der gewünschten Version
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # Nutze die neueste Hugo-Version
          extended: true # Aktiviere die Extended-Version für SCSS/SASS

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build Hugo site
        # Baut die statische Website mit Hugo
        run: hugo --minify

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Lint Code
        run: node node_modules/prettier/bin/prettier.cjs --check .

      - name: Upload via FTP (Robust lftp)
        # Use lftp for more control and reliability
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -c "set ssl:verify-certificate no; set mirror:set-permissions no; open -u ${{ secrets.USERNAME }},${{ secrets.PASSWORD }} ${{ secrets.SERVER }}; mirror --reverse --verbose --delete --exclude .git/ --exclude node_modules/ ./public/ ${{ secrets.PATH }}; quit"
